name: datamining
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26=hecd8cb5_2
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - ncurses=6.3=hca72f7f_0
  - openssl=1.1.1l=h9ed2024_0
  - pip=21.2.4=py39hecd8cb5_0
  - python=3.9.0=h88f2d9e_2
  - readline=8.1=h9ed2024_0
  - setuptools=58.0.4=py39hecd8cb5_0
  - sqlite=3.36.0=hce871da_0
  - tk=8.6.11=h7bc2e8c_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - alabaster==0.7.12
    - anyio==3.3.4
    - appnope==0.1.2
    - argon2-cffi==21.1.0
    - asgiref==3.4.1
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - blis==0.7.5
    - catalogue==2.0.6
    - certifi==2021.5.30
    - cffi==1.15.0
    - charset-normalizer==2.0.6
    - click==8.0.1
    - cssselect==1.1.0
    - cycler==0.11.0
    - cymem==2.0.6
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - dj-database-url==0.5.0
    - django==3.2.7
    - django-heroku==0.3.1
    - djangorestframework==3.12.4
    - dnspython==2.1.0
    - docutils==0.17.1
    - en-core-web-sm==3.1.0
    - entrypoints==0.3
    - et-xmlfile==1.1.0
    - feedfinder2==0.0.4
    - feedparser==6.0.8
    - filelock==3.0.12
    - flask==2.0.1
    - idna==3.2
    - imagesize==1.2.0
    - imbalanced-learn==0.8.1
    - imblearn==0.0
    - ipykernel==6.5.0
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - itsdangerous==2.0.1
    - jedi==0.18.0
    - jieba3k==0.35.1
    - jinja2==3.0.1
    - joblib==1.0.1
    - json5==0.9.6
    - jsonschema==4.1.2
    - jupyter-client==7.0.6
    - jupyter-core==4.9.1
    - jupyter-server==1.11.2
    - jupyterlab==3.2.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - kiwisolver==1.3.2
    - llvmlite==0.37.0
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mongoengine==0.23.1
    - murmurhash==1.0.6
    - nbclassic==0.3.4
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - newspaper3k==0.2.8
    - nltk==3.6.3
    - notebook==6.4.5
    - numba==0.54.1
    - numpy==1.20.3
    - oauthlib==3.1.1
    - openpyxl==3.0.9
    - packaging==21.0
    - pandas==1.3.4
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pathy==0.6.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.3.2
    - plotly==5.3.1
    - preshed==3.0.6
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.21
    - psycopg2==2.9.1
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pydantic==1.8.2
    - pygments==2.10.0
    - pymongo==3.12.1
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-decouple==3.4
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - regex==2021.9.24
    - requests==2.26.0
    - requests-file==1.5.1
    - requests-oauthlib==1.3.0
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sgmllib3k==1.0.0
    - six==1.16.0
    - sklearn==0.0
    - smart-open==5.2.1
    - sniffio==1.2.0
    - snowballstemmer==2.1.0
    - soupsieve==2.2.1
    - spacy==3.1.4
    - spacy-legacy==3.0.8
    - sphinx==4.2.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlparse==0.4.2
    - srsly==2.4.2
    - tenacity==8.0.1
    - terminado==0.12.1
    - testpath==0.5.0
    - thinc==8.0.12
    - threadpoolctl==3.0.0
    - tinysegmenter==0.3
    - tldextract==3.1.2
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - tweepy==3.10.0
    - typer==0.4.0
    - typing-extensions==3.10.0.2
    - umap-learn==0.3.10
    - urllib3==1.26.6
    - wasabi==0.8.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - werkzeug==2.0.1
    - whitenoise==5.3.0
    - xmltodict==0.12.0
prefix: /opt/miniconda3/envs/datamining
